DROP PROCEDURE IF EXISTS cursor_ROWPERROW;
DELIMITER ;;

CREATE PROCEDURE ROWPERROW()
BEGIN
DECLARE n INT DEFAULT 0;
DECLARE i INT DEFAULT 0;
SELECT COUNT(*) FROM inputdata INTO n;
SET i=0;
WHILE i<n DO 

  INSERT INTO table_B(id, vals) SELECT (ID, VAL) FROM table_A LIMIT i, 1;

  INSERT INTO table_B(id, vals)   SELECT MIN(LEVENSHTEIN("pizza", c1)) AS vals FROM listTab LIMIT i, 1;

  CALL str_split2("pizza de framboesa");

  SET i = i + 1;
END WHILE;
End;
;;

DELIMITER ;
